"""

	constants.py
	di MARIO GABRIELE CAROFANO

	Questo file raccoglie tutti i valori costanti utilizzati nei file di progetto.

"""

from enum import Enum

#	########################################################################	#
#	COSTANTI

SPOTIFY_SCOPE = "user-read-private playlist-read-private playlist-modify-private playlist-modify-public"
""" Ambiti di autorizzazione richiesti all'utente durante l'autenticazione Spotify. """

SPOTIFY_CACHE_PATH = ".spotify_cache"
""" Path del file dove il pacchetto Spotipy salva il token. """

SPOTIFY_REQUEST_LIMIT = 50
""" Numero massimo di brani da richiedere per chiamata alle API di Spotify. """

SPOTIFY_ARTISTS_LIMIT = 4
""" Numero massimo di artisti da includere nella stringa della traccia. """

SPOTIFY_QUERY_LIMIT = 5
""" Limite massimo di risultati di una ricerca su Spotify. """

YOUTUBE_DURATION_LIMIT = 600
""" Limite massimo di secondi della durata di un video Youtube. """

YOUTUBE_QUERY_LIMIT = 5
""" Limite massimo di risultati di una ricerca su Youtube. """

MAX_YOUTUBE_RESULTS = 50
""" Numero massimo di risultati che si possono ottenere da una singola ricerca su YouTube. """

YOUTUBE_VERIFIED_STRING = "auto-generated by youtube"
""" Stringa utilizzata per identificare i video verificati su YouTube. """

YOUTUBE_MARGIN_SECONDS = 10
""" Margine di tolleranza (in secondi) per la durata di un video Youtube rispetto alla traccia Spotify. """

YOUTUBE_EXTENDED_EXCLUDED_KEYWORDS = ["live", "remix", "cover"]
""" Parole chiave che, se presenti nel titolo di un video Youtube, ne escludono la selezione per una traccia 'extended mix'. """

YOUTUBE_EXTENDED_INCLUDED_KEYWORDS = ["extended", "extended mix"]
""" Parole chiave che devono essere presenti nel titolo di un video Youtube per essere selezionato come traccia 'extended mix'. """

YOUTUBE_SEARCH_OPTIONS = {
	"skip_download": True,
	"quiet": True,
	"no_warnings": True,
	"ignoreerrors": True,
	"extract_flat": True,
}
""" Opzioni di configurazione di yt-dlp per la ricerca di video senza download. """

YOUTUBE_DOWNLOAD_AUDIO_OPTIONS = {
	"format": "bestaudio/best",
	"postprocessors": [{
		"key": "FFmpegExtractAudio",
		"preferredcodec": "mp3",
		"preferredquality": "192",
	}],
	"quiet": True,
	"no_warnings": True
}
""" Opzioni di yt-dlp per scaricare e convertire i video in file audio MP3. """

YOUTUBE_DOWNLOAD_VIDEO_OPTIONS = {
    "format": "bestvideo+bestaudio/best",
    "merge_output_format": "mkv",
    "noplaylist": True,
    "quiet": True,
    "no_warnings": True,
}
""" Opzioni di yt-dlp per scaricare i video alla risoluzione più alta disponibile. """

FFMPEG_PATH = "/opt/homebrew/bin/ffmpeg"
""" Percorso dell'eseguibile FFMPEG utilizzato da yt-dlp per la conversione dei file multimediali. """

#	########################################################################	#
#	ENUMERAZIONI

class QueryType(Enum):
	""" Definisce le tipologie di ricerca su YouTube utilizzabili per ciascuna traccia. """

	AUDIO		= "official audio"
	EXTENDED	= "extended mix"
	VIDEO		= "official video"
	LYRICS		= "lyrics"

	# end class

QUERY_LIST = list(QueryType)

class MenuItems(Enum):
	""" Definisce le voci disponibili nel menu interattivo. """
	
	# CREATE_PLAYLIST 	= "Crea playlist"
	# ADD_PLAYLIST		= "Aggiungi playlist da Spotify"
	# EDIT_PLAYLIST		= "Modifica playlist"
	PRINT_PLAYLIST		= "Visualizza playlist inserite"
	PROCESS_PLAYLIST	= "Cerca playlist su Youtube"
	DOWNLOAD_PLAYLIST	= "Scarica playlist da Youtube"
	EXIT				= "Esci"

	# end class

MENU_LIST = list(MenuItems)